- src/app/layout.tsx
- src/app/page.tsx
細かいことはコメントに書いています
背景色などはお好きにどうぞ...
> feat: 🎸 3列でのレイアウトとSP対応

- package.json
- pnpm-lock.yaml
- src/components/LinkMenu.tsx
- src/components/SpMenu.tsx
- tailwind.config.ts
close #12
- LinkMenuのgapを`gap-2`->`gap-3`としました
- SpMenuの背景にグラデーションを付けました
- SpMenuにアニメーションを付けました(開いたときだけ)
- heroiconsを消しました
なくてもいいかなと思ったので、SpMenuを閉じたときはアニメーションかけないようにしてます。
> メニューの微修正など

- next.config.mjs
> next.configの書き換え

- next.config.mjs
> next.configの修正

- .github/workflows/nextjs.yml
> ymlファイルの修正

- .github/workflows/nextjs.yml
Reverts frontend-conference-hokkaido-2024/landing-page-2024#44
> Revert "pre-release"

- src/components/elements/Paragraph.tsx
- tailwind.config.ts
> Paragraph実装

- src/app/globals.css
- tailwind.config.ts
close #93 
`tailwind.config.ts`に4つの固定値を設定
> tailwind.config.tsに固定値を設定

- src/components/ui/CommonButton.tsx
fix #95
共通ボタンに`className`の適用漏れがあったので対応
> 共通ボタンにclass名の適用

- src/components/elements/Title.tsx
fix #78
tracking-widerをあて忘れてたのであてました
> Titleの文字間隔修正

- .vscode/settings.json
- markuplint.config.ts
- package.json
- pnpm-lock.yaml
やっぱmarkuplint導入したいよね〜ということで導入. 
みなさん頑張ってください
> style: markuplintの導入

- src/app/layout.tsx
- src/app/page.tsx
> 2重mainタグの解消・padding修正

- src/components/CTAArea.tsx
- src/components/ui/CommonButton.tsx
close #120 
asChildの実装
子要素に`leftIcon`や`rightIcon`、`<span>`などがある状態でasChildをやるとbutton全体がLinkになってくれないです。そのため、アイコンを受け取るのはやめて、素直に`children`だけ受け取る実装にしました。
残り時間との兼ね合いも考えて、いったんはこの方針で行きたいです。
```tsx
<CommonButton
background="bg-gradient-to-r from-pink-500 to-blue-500"
asChild
>
<Link href="https://example.com">
<Image src={"images/Icon/icon_bear.png"} alt={""} width={18} height={18} />
<span className="px-2.5">ああああああああ</span>
</Link>
</CommonButton>
```
> asChildの実装

- .github/workflows/nextjs.yml
> pre-release

- package.json
- pnpm-lock.yaml
- src/app/layout.tsx
- src/components/TopVisual.tsx
- src/components/menu/MenuList.tsx
- src/components/ui/separator.tsx
close #88
- メニューリストコンポーネントを実装しました
- `TopVisual.tsx`で警告吐いてたので直しました(前にも直した気がする)
scroll先のid指定はコンフリクトするのが怖いので別issueに切るなりしたいです
> メニューリストコンポーネントの実装

- src/app/@avatarList/page.tsx
- src/app/@staffBlog/page.tsx
403でactionsにコケるのでエラーのボディを表示するようにする
> error body表示

- src/app/@sponsorSection/page.tsx
- src/components/AccessInfo.tsx
- src/components/EventOverView.tsx
- src/components/Online.tsx
- src/components/menu/MenuList.tsx
close #144 
`#staff`は修正中のため未対応
> 移動先にidを設定する

- src/components/EventOverView.tsx
> EventOverview修正

- src/app/job-board/@jobBoardSection/data/constants.ts
余計なことは考えず、ジョブボード情報の入力のみ行いました
デザイン崩れなどの微妙なところは別で。
> ジョブボード情報の入力

- src/app/job-board/@jobBoardSection/data/constants.ts
> スポンサージョブボード　追加スポンサー分反映

- src/app/job-board/@jobBoardSection/data/constants.ts
- src/components/coreStaffSection/CoreStaffSection.tsx
- ジョブボードに株式会社ゆめみさんをついか
- `コアスタッフ` -> `スタッフ`に表記変更
> ジョブボード要素の追加・文言修正

- src/components/coreStaffSection/CoreStaffSection.tsx
> 不要なマージンを削除

- src/components/Avatar.tsx
- src/components/coreStaffSection/CoreStaffSection.tsx
close #182
スタッフの名前をクリックすると、設定済みのSNSアカウントに移動できます
> スタッフの名前から該当スタッフのSNSに移動できるように

- src/app/page.tsx
- src/asset/Vector/icon_camera.svg
- src/components/Photos.tsx
- src/components/images/icon/Camera.tsx
> 当日の写真のgoogleフォトへのリンクを設置

- CNAME
Reverts frontend-conference-hokkaido-2024/landing-page-2024#207
> Revert "release"
